torch_frame_model:
  channels: 128
  num_layers: 1
  text_embedder: bert
model:
  channels: 128
  aggr: "sum"
  conv: "sage"
  num_layers: 2
  use_self_join: false
  use_self_join_with_retrieval: false
  perturb_edges: null
  feature_dropout: 0.0
selfjoin:
  node_type_considered: "facilities"
  num_filtered: 20
  sim_score_type: 'attention'  # 'cos', 'L2', 'attention'
  aggr_scheme: 'mpnn'  # 'gat', 'mpnn'
  normalize_score: true
  aggr: 'sum'
dataset:
  name: "rel-trial"
  cache_dir: "/dfs/scratch0/joshrob/projects/relbench/cache"
  root_dir: "/dfs/scratch0/joshrob/projects/relbench/data"
  task: "rel-trial-site"
  # All tasks:
  # rel-stackex: rel-stackex-engage, rel-stackex-votes, rel-stackex-badges
  # rel-amazon: rel-amazon-churn, rel-amazon-ltv, rel-amazon-product-churn, rel-amazon-product-ltv
loader:
  num_neighbors: 128
  num_workers: 1
  batch_size: 512
  temporal_strategy: 'uniform'
optim:
  max_epoch: 30
  early_stop: 10
  base_lr: 0.01
seed: 42
