torch_frame_model:
  channels: 128
  num_layers: 2
  torch_frame_model_cls: "ResNet"
  text_embedder: "glove"
model:
  channels: 128
  aggr: "sum"
  conv: "sage"
  num_layers: 2
  perturb_edges: null
  mask_features: false
  feature_dropout: 0.0
  use_shallow: true
dataset:
  name: "rel-math-stackex"
  cache_dir: "/dfs/scratch0/joshrob/projects/relbench/cache"
  root_dir: "/dfs/scratch0/joshrob/projects/relbench/data"
  task: "rel-stackex-comment-on-post"
loader:
  num_neighbors: 160
  num_workers: 0
  batch_size: 512
  temporal_strategy: 'uniform'
  share_same_time: true
optim:
  max_epoch: 30
  early_stop: 10
  base_lr: 0.01
seed: 42
train:
  eval_period: 30